CREATE TABLE PLAYER_TABLE (PLAYERID INTEGER PRIMARY KEY,PLAYERNAME CHAR(20),PLAYERAGE INTEGER,PLAYERGENDER CHAR(10));
CREATE TABLE RECORD_TABLE (PLAYERID INTEGER ,BESTSCORE INTEGER,SCOREDATE DATE);
CREATE TABLE SCORE_TABLE (PLAYERID INTEGER ,LEVELPASSED INTEGER,TOTALSCORE INTEGER);
CREATE TABLE HINT_TABLE (TOPIC CHAR(20),WORD CHAR(20),HINT1 CHAR(40),HINT2 CHAR(40));