CREATE TABLE HINT_TABLE(TOPIC VARCHAR(50),WORD VARCHAR(50),HINT1 VARCHAR(200),HINT2 VARCHAR(200),LEVELNUM INTEGER);
INSERT INTO HINT_TABLE VALUES('Color','pink','HINT:It is a name of color.','HINT:Jaipur is called the ____ city.',1);
INSERT INTO HINT_TABLE VALUES('Color','cyan','HINT:It is a name of color.','HINT:It is one of the primary color in CMYK color model.',1);
INSERT INTO HINT_TABLE VALUES('Color','blue','HINT:It is a name of color.','HINT:It is the primary color in the RBY color model',1);
INSERT INTO HINT_TABLE VALUES('Color','gold','HINT:It is a name of color.','HINT:It is a metallic color.A noble metal.',1);
INSERT INTO HINT_TABLE VALUES('Color','lime','HINT:It is a name of color.','HINT:It is a representation of the color of the citrus fruit',1);
INSERT INTO HINT_TABLE VALUES('Color','navy','HINT:It is a name of color.','HINT: It is a very dark shade of blue.',1);
INSERT INTO HINT_TABLE VALUES('Color','grey','HINT:It is a name of color.','HINT:It is an intermediate color btw black and white.',1);
INSERT INTO HINT_TABLE VALUES('Color','ruby','HINT:It is a name of color.','HINT:It is a represention of color of the cut and polished _____ gemstone.',1);
INSERT INTO HINT_TABLE VALUES('Colour','black',"HINT:its the name of a colour","HINT:colour wiyhout hue",2);
INSERT INTO HINT_TABLE VALUES('Colour','brown',"HINT:its the name of a colour","HINT:colour of a part of tree",2);
INSERT INTO HINT_TABLE VALUES('Colour','blush',"HINT:its the name of a colour","HINT:white tone of red violet",2);
INSERT INTO HINT_TABLE VALUES('Colour','blond',"HINT:its the name of a colour","HINT:used to colour hairs",2);
INSERT INTO HINT_TABLE VALUES('Colour','white',"HINT:its the name of a colour","HINT:its achromatic",2);
INSERT INTO HINT_TABLE VALUES('Colour','peach',"HINT:its the name of a colour","HINT:colour of interior flesh of a fruit",2);
INSERT INTO HINT_TABLE VALUES('Colour','lemon',"HINT:its the name of a colour","HINT:a fruit has same name",2);
INSERT INTO HINT_TABLE VALUES('Sports','polo',"HINT1-its the name of sport","HINT2-it includes horses",1);
INSERT INTO HINT_TABLE VALUES('Sports','ludo',"HINT1-its the name of sport","HINT2-board game for four players",1);
INSERT INTO HINT_TABLE VALUES('Sports','golf',"HINT1-its the name of sport","HINT2-club and ball sport",1);
INSERT INTO HINT_TABLE VALUES('Sports','sumo',"HINT1-its the name of sport","HINT2-Japan's national sport",1);
INSERT INTO HINT_TABLE VALUES('Sports','chess',"HINT1-its the name of sport","HINT2-board game for two players",2);
INSERT INTO HINT_TABLE VALUES('Sports','poker',"HINT1-its the name of sport","HINT2-cards game with any no of cards",2);
INSERT INTO HINT_TABLE VALUES('Sports','rummy',"HINT1-its the name of sport","HINT2-card game based on matching of cards",2);
INSERT INTO HINT_TABLE VALUES('Sports','rugby',"HINT1-its the name of sport","HINT2-played by an oval ball",2);
INSERT INTO HInT_TABLE VALUES('City','bhuj',"HINT1-Name of a city","HINT2-famous for earthquake in 2001",1);		
INSERT INTO HINT_TABLE VALUES('City','gaya',"HINT1-Name of a city","HINT2-known as birthplace of buddhism",1);
INSERT INTO HINT_TABLE VALUES('City','rome',"HINT1-Name of a city","HINT2-has seven hills",1);
INSERT INTO HINT_TABLE VALUES('City','bali',"HINT1-Name of a city","HINT2-an indonasian island",1);
INSERT INTO HINT_TABLE VALUES('City','mhow',"HINT1-Name of a city","HINT2-famous defence city of M.P.",1);
INSERT INTO HINT_TABLE VALUES('City','agra',"HINT1-Name of a city","HINT2-known for a particular sweat dish",1);
INSERT INTO HINT_TABLE VALUES('City','paris',"HINT1-Name of a ctiy","HINT2-city of cafes",2);
INSERT INTO HINT_TABLE VALUES('City','kabul',"HINT1-Name of a city","HINT2-was a mecca for young western hippies",2);
INSERT INTO HINT_TABLE VALUES('City','tokyo',"HINT1-Name of a city","HINT2-most populated city",2);
INSERT INTO HINT_TABLE VALUES('City','delhi',"HINT1-Name of a city","HINT2-capital of mughals",2);
INSERT INTO HINT_TABLE VALUES('City','hanoi',"HINT1-Name of a city","HINT2-second largest city of its vietnam",2);
INSERT INTO HINT_TABLE VALUES('City','dhaka',"HINT1-Name of a city","HINT2-was a part of india till 1971",2);
INSERT INTO HINT_TABLE	VALUES('Animal','hare',"HINT1-Name of an animal","HINT2-similar to rabbits",1);
INSERT INTO HINT_TABLE	VALUES('Animal','hogg',"HINT1-Name of an animal","HINT2-weigh around 100 Kgs",1);
INSERT INTO HINT_TABLE	VALUES('Animal','bull',"HINT1-Name of an animal","HINT2-used to pull carts",1);
INSERT INTO HINT_TABLE	VALUES('Animal','lion',"HINT1-Name of an animal","HINT2-king of carnivores",1);
INSERT INTO HINT_TABLE	VALUES('Animal','mule',"HINT1-Name of an animal","HINT2-combination of horse and donkey",1);
INSERT INTO HINT_TABLE	VALUES('Animal','lamb',"HINT1-Name of an animal","HINT2-follows their companions in groups",1);
INSERT INTO HINT_TABLE	VALUES('Animal','mole',"HINT1-Name of an animal","HINT2-crete tunnel and forage for their food",1);
INSERT INTO HINT_TABLE	VALUES('Animal','goat',"HINT1-Name of an animal","HINT2-herbivore animal",1);
INSERT INTO HINT_TABLE	VALUES('Animal','deer',"HINT1-Name of an animal","HINT2-are hoofed ruminant mamals",1);
INSERT INTO HINT_TABLE	VALUES('Animal','bear',"HINT1-Name of an animal","HINT2-carnivoran mamals",1);
INSERT INTO HINT_TABLE	VALUES('Animal','tiger',"HINT1-Name of an animal","HINT2-strongest amongst canivorian family",2);
INSERT INTO HINT_TABLE	VALUES('Animal','shark',"HINT1-Name of an animal","HNIT2-aquatic animal",2);
INSERT INTO HINT_TABLE	VALUES('Animal','horse',"HINT1-Name of an animal","HINT2-used for riding at hilly regions",2);
INSERT INTO HINT_TABLE	VALUES('Animal','mouse',"HINT1-Name of an animal","HINT2-has pointed snout and rounded ears",2);
INSERT INTO HINT_TABLE	VALUES('Animal','whale',"HINT1-Name of an animal","HINT2-largest aquatic animal",2);
INSERT INTO HINT_TABLE	VALUES('Brands','nike',"HINT1-Name of a brand","HINT2-popular for making shoes",1);
INSERT INTO HINT_TABLE	VALUES('Brands','dell',"HINT1-Name of a brand","HINT2-large scale laptops and P.C.s brand",1);
INSERT INTO HINT_TABLE	VALUES('Brands','sony',"HINT1-Name of a brand","HINT2-is known for its televisions",1);
INSERT INTO HINT_TABLE	VALUES('Brands','bata',"HINT1-Name of a brand","HINT2-old footwear brand",1);
INSERT INTO HINT_TABLE	VALUES('Brands','boat',"HINT1-Name of a brand","HINT2-headphones and headsets brand",1);
INSERT INTO HINT_TABLE	VALUES('Brands','apple',"HINT1-Name of a brand","HINT2-american brand of electronics",2);
INSERT INTO HINT_TABLE	VALUES('Brands','redmi',"HINT1-Name of a brand","HINT2-mobile making brand",2);
INSERT INTO HINT_TABLE	VALUES('Brands','pepsi',"HINT1-Name of a brand","HINT2-cold drinks brand",2);
INSERT INTO HINT_TABLE	VALUES('Brands','maped',"HINT1-Name of a brand","HINT2-popular stationary items brand",2);
INSERT INTO HINT_TABLE	VALUES('Brands','honda',"HINT1-Name of a brand","HINT2-car brand",2);
INSERT INTO HINT_TABLE VALUES('Birds','crow',"HINT1-Name of bird","HINT2-bird of genus corvus",1);
INSERT INTO HINT_TABLE	VALUES('Birds','dove',"HINT1-Name of bird","HINT2-same as pigeons family",1);
INSERT INTO HINT_TABLE	VALUES('Birds','hawk',"HINT1-Name of bird","HINT2- group of medium-sized diurnal birds of prey of the family Accipitridae",1);
INSERT INTO HINT_TABLE	VALUES('Birds','kite',"HINT1-Name of bird","HINT2-smaller version of eagles",1);
INSERT INTO HINT_TABLE	VALUES('Birds','kiwi',"HINT1-Name of bird","HINT2-national bird of new zealand",1);
INSERT INTO HINT_TABLE	VALUES('Birds','eagle',"HINT1-Name of bird","HINT2-symbol of war and imperial power",2);
INSERT INTO HINT_TABLE	VALUES('Birds','goose',"HINT1-Name of bird","HINT2-has a long black neck and white strip on cheek",2);
INSERT INTO HINT_TABLE	VALUES('Birds','finch',"HINT1-Name of bird","HINT2-have stout conical bills adapted for eating seeds and nuts",2);
INSERT INTO HINT_TABLE	VALUES('Birds','crane',"HINT1-Name of bird","HINT2-long-necked birds in the group Gruiformes",2);
INSERT INTO HINT_TABLE	VALUES('Birds','swift',"HINT1-Name of bird","HINT2-one of the most fastest bird",2);
